CREATE TABLE DEPART (

NUMERO_DU_PASSAGER int,
NUMERO_DU_BILLET varchar(50),
NUMERO_SECURITE_SOCIALE varchar(50),
NUMERO_DU_VOL varchar(50),
NUMERO_ENREGISTREMENT varchar(50),
DATE_DE_DEPART date,
PLACES_LIBRES int,
PLACES_OCCUPEES int,

foreign key (NUMERO_DU_BILLET) 			references BILLET(NUMERO_DU_BILLET),
foreign key (NUMERO_SECURITE_SOCIALE) 	references SALARIE(NUMERO_SECURITE_SOCIALE),
foreign key (NUMERO_DU_VOL) 			references VOL(NUMERO_DU_VOL),
foreign key (NUMERO_ENREGISTREMENT)    	references AVION(NUMERO_ENREGISTREMENT),
foreign key (DATE_DE_DEPART)    		references VOL(HEURE_DEPART)

);